apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-nginx
  labels:
    app: challenge-nginx
spec:
  replicas: 3
  selector:
      matchLabels:
        app: challenge-nginx
  template:
    metadata:
      labels:
        app: challenge-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80

        volumeMounts:
        - mountPath: /usr/share/nginx/html
          readOnly: true
          name: nginx-index

      volumes:
      - name: nginx-index
        configMap:
          name: nginx-index
          items:
            - key: index.html
              path: index.html
